import { VoiceStyle, VoiceModelOption } from "./types";

export const VOICE_STYLES: VoiceStyle[] = [
  {
    id: "story-narrator",
    name: "Story Narrator",
    burmeseName: "ပုံပြင်ပြောသူ",
    description: "Classic cinematic storytelling with rich modulation and narrative depth.",
    icon: "BookOpen",
    defaultVoice: "Charon",
    defaultSpeed: 0.95,
    defaultWarmth: 0.8,
    defaultEmotion: 0.7,
    promptGuideline: "Narrate this like a magical, ancient legend. Let your voice carry depth, wisdom, and theatrical suspense.",
  },
  {
    id: "warm-female",
    name: "Warm Female",
    burmeseName: "နွေးထွေးသော အမျိုးသမီး",
    description: "Gentle, compassionate and comforting voice suitable for emotional stories or audiobooks.",
    icon: "Heart",
    defaultVoice: "Kore",
    defaultSpeed: 1.0,
    defaultWarmth: 0.9,
    defaultEmotion: 0.6,
    promptGuideline: "Speak with a gentle, smiling tone. Let your voice feel like a warm, comforting hug on a rainy evening.",
  },
  {
    id: "calm-male",
    name: "Calm Male",
    burmeseName: "တည်ငြိမ်သော အမျိုးသား",
    description: "Steady, authoritative and reassuring male voice with clear enunciation.",
    icon: "User",
    defaultVoice: "Fenrir",
    defaultSpeed: 1.0,
    defaultWarmth: 0.7,
    defaultEmotion: 0.4,
    promptGuideline: "Deliver the text with absolute calmness, steady confidence, and stable rhythm. Keep it reassuring.",
  },
  {
    id: "documentary",
    name: "Documentary",
    burmeseName: "မှတ်တမ်းတင် စကားပြော",
    description: "Professional, objective, clear and articulate voice for historical or educational scripts.",
    icon: "Mic",
    defaultVoice: "Zephyr",
    defaultSpeed: 1.05,
    defaultWarmth: 0.5,
    defaultEmotion: 0.3,
    promptGuideline: "Speak with professional clarity, informative weight, and absolute articulate precision as a national geographic narrator.",
  },
  {
    id: "emotional",
    name: "Emotional",
    burmeseName: "စိတ်ခံစားမှု အပြည့်",
    description: "High expressive vocal range with deep feelings of empathy, passion or drama.",
    icon: "Flame",
    defaultVoice: "Kore",
    defaultSpeed: 0.9,
    defaultWarmth: 0.8,
    defaultEmotion: 0.9,
    promptGuideline: "Pour your heart and soul into every word. Let your voice tremble slightly with pure raw emotion, dramatic weight, and intense feeling.",
  },
  {
    id: "sad",
    name: "Sad / Melancholic",
    burmeseName: "ဝမ်းနည်းဖွယ်ရာ",
    description: "Slower tempo with heavy, soft breath and somber, melancholic resonance.",
    icon: "CloudRain",
    defaultVoice: "Charon",
    defaultSpeed: 0.85,
    defaultWarmth: 0.6,
    defaultEmotion: 0.85,
    promptGuideline: "Speak with a slow, heavy, sighing voice. Introduce natural melancholic pauses, feeling the weight of grief or sadness in each syllable.",
  },
  {
    id: "happy",
    name: "Happy / Energetic",
    burmeseName: "ပျော်ရွှင်တက်ကြွသော",
    description: "Bright, cheerful, high-spirited voice with rhythmic uptempo delivery.",
    icon: "Sparkles",
    defaultVoice: "Puck",
    defaultSpeed: 1.1,
    defaultWarmth: 0.8,
    defaultEmotion: 0.8,
    promptGuideline: "Radiate immense joy, laughter, and high energy! Speak with a lively bounce, bright cadence, and cheerful smile in your voice.",
  },
  {
    id: "whisper",
    name: "Whisper / Intimate",
    burmeseName: "တိုးတိုးလေးပြောသူ",
    description: "Airy, soft, low-volume speech perfect for dramatic suspense or cozy bedtime stories.",
    icon: "Wind",
    defaultVoice: "Zephyr",
    defaultSpeed: 0.9,
    defaultWarmth: 0.8,
    defaultEmotion: 0.6,
    promptGuideline: "Speak in an extremely quiet, whispered, airy breathy tone. Almost like sharing a sacred secret directly in the listener's ear.",
  },
];

export const VOICE_MODELS: VoiceModelOption[] = [
  {
    id: "Kore",
    name: "Kore",
    gender: "Female",
    description: "Clear, warm, melodic and extremely versatile female tone.",
  },
  {
    id: "Fenrir",
    name: "Fenrir",
    gender: "Male",
    description: "Steady, robust, centered and comforting male resonance.",
  },
  {
    id: "Puck",
    name: "Puck",
    gender: "Female",
    description: "Bright, youthful, energetic and clear female narrative tone.",
  },
  {
    id: "Charon",
    name: "Charon",
    gender: "Male",
    description: "Deep, mature, theatrical and heavy cinematic male tone.",
  },
  {
    id: "Zephyr",
    name: "Zephyr",
    gender: "Female",
    description: "Calm, airy, crisp and articulate female informational tone.",
  },
];

export const SAMPLE_SCRIPTS = [
  {
    title: "The Mysterious Forest (Fantasy)",
    category: "Fantasy Story",
    text: "ဟိုးရှေးရှေးတုန်းက သာယာလှပတဲ့ တောအုပ်ကြီးတစ်ခုထဲမှာ အလွန်ဉာဏ်ကောင်းတဲ့ ယုန်ကလေးတစ်ကောင် ရှိသတဲ့။ ယုန်ကလေးဟာ နေ့စဉ်နေ့တိုင်း သူငယ်ချင်းတွေနဲ့အတူ ပျော်ပျော်ရွှင်ရွှင် ဆော့ကစားလေ့ရှိပြီး စိတ်နှလုံး ဖြူစင်လှပါတယ်။ တစ်နေ့မှာတော့ တောအုပ်ကြီးထဲကို ဗလကြီးမားတဲ့ ခြင်္သေ့ဆိုးကြီးတစ်ကောင် ရောက်ရှိလာခဲ့ပြီး တောတိရစ္ဆာန်လေးတွေကို ခြိမ်းခြောက်ပါတော့တယ်။ ဒါပေမယ့် ဉာဏ်ကောင်းတဲ့ ယုန်ကလေးကတော့ ကြောက်ရွံ့မသွားဘဲ တောအုပ်ကြီး ငြိမ်းချမ်းဖို့အတွက် အစီအစဉ်တစ်ခု စတင်လိုက်ပါတော့တယ်။",
  },
  {
    title: "Mother's Undying Love (Melodrama)",
    category: "Emotional",
    text: "အမေဆိုတာ သားသမီးတွေအတွက် ဘယ်တော့မှ မငြိမ်းသွားမယ့် ဆီမီးတိုင်တစ်လုံးပါ။ တစ်ခါတုန်းက အမေဖြစ်သူဟာ မုန်တိုင်းထန်တဲ့ ညတစ်ညမှာ ဖျားနာနေတဲ့ သားဖြစ်သူရဲ့ ကုတင်ဘေးကနေ တစ်ဖဝါးမှမခွာဘဲ ပြုစုပေးခဲ့ပါတယ်။ သူ့ကိုယ်ပိုင် အနွေးထည်ကိုတောင် ချွတ်ပြီး သားဖြစ်သူကို ခြုံပေးထားခဲ့လို့ အမေကိုယ်တိုင် အေးစိမ့်တဲ့ဒဏ်ကို အံကြိတ်ခံခဲ့ရရှာပါတယ်။ သားဖြစ်သူ နိုးလာတဲ့အခါမှာတော့ အမေရဲ့လက်ကလေးတွေဟာ အေးစက်နေပြီး မျက်နှာထက်မှာတော့ ချိုသာတဲ့ အပြုံးတစ်ခုက ဖုံးလွှမ်းလျက် ရှိနေခဲ့ပါတယ်။",
  },
  {
    title: "Myanmar Heritage (Documentary)",
    category: "Historical",
    text: "ရှေးဟောင်းသမိုင်းဝင် ပုဂံမြို့တော်ကြီးဟာ မြန်မာနိုင်ငံရဲ့ အမွေအနှစ် ယဉ်ကျေးမှု ပြယုဂ်တစ်ခု ဖြစ်ပါတယ်။ သက္ကရာဇ် ၁၁ ရာစုကတည်းက တည်ဆောက်ခဲ့တဲ့ စေတီပုထိုးပေါင်း ထောင်ချီဟာ ဧရာဝတီမြစ်ကမ်းဘေးမှာ ခန့်ညားထည်ဝါစွာ တည်ရှိနေပါတယ်။ နေဝင်ဆည်းဆာ အချိန်မှာ ပုဂံမြေပြင်ကို ငေးမောကြည့်ရင် ရွှေရောင်တောက်ပနေတဲ့ ဘုရားကျောင်းကန်တွေနဲ့ ရှေးဟောင်းအနုပညာ ဗိသုကာလက်ရာတွေကို မြင်တွေ့ရပြီး၊ သမိုင်းရဲ့ ကြီးကျယ်ခမ်းနားမှုတွေကို ခံစားရစေမှာ ဖြစ်ပါတယ်။",
  },
];
